=== jokesterfr/cvlyzer/data/cv.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cv (contact, section+)>
<!ATTLIST cv xml:lang NMTOKEN #REQUIRED>

<!-- CONTACT -->
<!ELEMENT contact (name, address, phone, email, homepage, photo?, keywords?)>
<!ATTLIST contact title CDATA #REQUIRED>

<!ELEMENT name (CDATA)>
<!ATTLIST name title CDATA #REQUIRED>

<!ELEMENT address (#PCDATA)>
<!ATTLIST address title CDATA #REQUIRED>

<!ELEMENT phone (CDATA)>
<!ATTLIST phone title CDATA #REQUIRED>

<!ELEMENT email (CDATA)>
<!ATTLIST email title CDATA #REQUIRED>

<!ELEMENT homepage (CDATA)>
<!ATTLIST homepage title CDATA #REQUIRED>

<!ELEMENT photo (CDATA)>
<!ATTLIST photo title CDATA #REQUIRED>

<!ELEMENT keywords (CDATA)><!-- Comma separated -->
<!ATTLIST keywords title CDATA #IMPLIED>
<!-- END OF CONTACT -->


<!-- SECTION -->
<!ELEMENT section (subsection*|item*)>
<!ATTLIST section title CDATA #REQUIRED>
<!-- END OF SECTION -->


<!-- SUBSECTION -->
<!ELEMENT subsection (item)+>
<!ATTLIST subsection title CDATA #REQUIRED>
<!ATTLIST subsection date CDATA #IMPLIED>
<!-- END OF SUBSECTION -->


<!-- ITEM -->
<!ELEMENT item (#PCDATA)>
<!ATTLIST item title CDATA #IMPLIED>
<!-- END OF ITEM -->

<!-- XHTML COMPONENTS -->
<!ELEMENT a (#PCDATA)>
<!ATTLIST a href CDATA #REQUIRED>
<!ATTLIST a alt CDATA #IMPLIED>
<!ATTLIST a target CDATA #IMPLIED>

<!ELEMENT em (#PCDATA)>

<!ELEMENT dfn (#PCDATA)>
<!-- END OF XHTML COMPONENTS -->

=== jokesterfr/cvlyzer/src/cv_fr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/cv2html5.xsl"?>

<cv lang="fr" suffix="_clement_desiles_2020">
  <contact title="Contact">
    <name title="Name">Cl√©ment D√©siles</name>
    <title>D√©veloppeur Node.js exp√©riment√© - Ing√©nieur avant-vente</title>
    <info>31 ans ‚Äì permis de conduire B</info>
    <phone>+33 6 58 12 45 61</phone>
    <email>clementdesilesfr@gmail.com</email>
    <homepage>https://clementdesiles.fr</homepage>
    <photo width="128">img/photo.png</photo>
    <keywords>curriculum vitae, pre-sales engineer, engineering, Node.js, full-stack, Linux, CI, CD, Ansible</keywords>
  </contact>

  <section title="Formation">
    <subsection title="Dipl√¥me d‚Äôing√©nieur, grade de Master" date="2007‚Äì2012">
      <item>Ecole Nationale d‚ÄôIng√©nieurs de Brest (<a href="https://www.enib.fr">ENIB</a>), France</item>
    </subsection>
    <subsection title="Semestre de mobilit√© √† l‚Äô√©tranger" date="2012">
      <item>Universit√© de Cadix (<a href="https://www.uca.es">UCA</a>), Espagne</item>
    </subsection>
  </section>

  <section title="Exp√©rience">
    <subsection title="Ing√©nieur avant-vente, Hoppen (ex. T√©l√©com Sant√©)" date="depuis juin 2016 ‚Äì 4 ans">
      <item>Avant-vente : mise en place de kits de d√©monstration, showroom, r√©ponse √† appel d'offre, chambres t√©moin, r√©alisation de devis.</item>
      <item>Export : accompagnement √† l‚Äôinternational (Portugal, Suisse, Quatar, Arabie Saoudite, Antilles), r√©ponse aux appels d‚Äôoffre, d√©mos, <dfn>KAM</dfn> et d√©ploiement.</item>
      <item>Lead dev : packaging <dfn>Docker</dfn>, migration de 800 sources logicielles <dfn>Gitlab</dfn>, mise en place de CI/CD (<dfn>Gitlab Runners</dfn>, <dfn>Ansible</dfn>, <dfn>Artifactory</dfn>). D√©ploiement de <dfn>Jira</dfn> pour nos 300 employ√©s.</item>
      <item>Interconnexion : dossiers m√©dicaux, radiographies, commande de repas, facturation, <dfn>GMAO</dfn>, <dfn>SSO</dfn>, domotique (<dfn>Siemens</dfn>, <dfn>KNX</dfn>).</item>
      <item>S√©curit√© : analyse de risque, hardening, veille, syst√®mes de paiement et d‚Äôauthentification.</item>
      <item>Handicap : POC d'IHM √† destination des personnes handicap√©es mentales et physique (contacteur sec, balayage au souffle, contr√¥le r√©tinien).</item>
    </subsection>
    <subsection title="VIE Architecte d√©veloppeur, Revevol Milan" date="mai 2015 √† mai 2016 ‚Äì 1 an">
      <item>Intranet international de 60 000 utilisateurs pour Lafarge-Holcim : devops d‚Äôune application <dfn>Google App Engine</dfn>.</item>
      <item>Migration des archives d'Airliquide dans le Cloud : d√©veloppement d'application web distribu√©e (US / Europe) sharding <dfn>MongoDB</dfn> dans la <dfn>GCP</dfn>.</item>
      <item>Outil IT de gestion de mobiles pour Solvay : application Web de gestion d'acc√®s pour les 30 000 smartphones connect√©s au domaine de l‚Äôentreprise (<dfn>Apps for Work</dfn>).</item>
    </subsection>
    <subsection title="D√©veloppeur full stack, T√©l√©com Sant√©" date="septembre 2012 √† avril 2015 ‚Äì 3 ans et 6 mois">
      <item>D√©veloppeur : architecture d'applications web tactiles, <dfn>responsive design</dfn>, i18n, migration de code legacy.</item>
      <item>Encadrement : formation et suivi de stagiaires, transfert de comp√©tences, coordination de projet.</item>
      <item>Conception : analyse, cahier des charges, sp√©cifications logicielles, int√©gration, tests, packaging.</item>
      <item>Syst√®me : support de tablettes tactiles sous <dfn>Linux</dfn>, <dfn>reverse engineering</dfn>, √©criture de drivers, bindings <dfn>C</dfn>/<dfn>Node.js</dfn>.</item>
    </subsection>
    <subsection title="Stage ing√©nieur, T√©l√©com Sant√©" date="de f√©vrier 2012 √† ao√ªt 2012 ‚Äì 6 mois">
      <item>Au sein d'une jeune startup (2 fondateurs, un dev senior et moi-m√™me), d√©veloppement d'une tablette √† destination des patients hospitalis√©s. Support <dfn>Linux</dfn>, d√©veloppement d‚Äôapplications <dfn>Web</dfn> et <dfn>Node.js v0.6</dfn>.</item>
    </subsection>
    <subsection title="Auto-entrepreneur, d√©veloppement logiciel" date="de septembre 2011 √† ao√ªt 2012 ‚Äì 1 an">
      <item>R√©alisation d‚Äôune plate-forme <dfn>e-Commerce</dfn> pour le site <a href="https://worldgift.com">WorldGift</a>.</item>
    </subsection>
    <subsection title="Stage, Telemotive, Munich" date="de juin 2010 √† d√©cembre 2010 ‚Äì 6 mois">
      <item>Au coeur de l'industrie automobile, d√©veloppement de services <dfn>UPnP</dfn> sur des cartes embarqu√©es <dfn>Linux</dfn> / <dfn>PowerPC</dfn>. √âtudes d'encapsulation de trames <dfn>Ethernet</dfn> dans un r√©seau fibre optique <dfn>MOST</dfn>. Analyse de performances (<dfn>Python</dfn>).</item>
    </subsection>
    <subsection title="Assistant Webmaster, PMB Services" date="de juin 2007 √† juin 2010 ‚Äì 3 ans">
      <item>Contributions √† un logiciel de gestion de biblioth√®que en <dfn>PHP</dfn> / <dfn>MySQL</dfn>, r√©alisation de chartes graphiques, d‚Äôinterfaces Web et du <a href="https://www.sigb.net">site internet</a> de la soci√©t√© avec le framework <dfn>SPIP</dfn>.</item>
    </subsection>
  </section>

  <section title="Comp√©tences">
    <subsection title="Informatique g√©n√©rale">
      <item>Langages : <dfn>Node.js, Python, C, C++, bash</dfn></item>
      <item>Administration syst√®me : <dfn>Ubuntu, Archlinux, LFS, Ansible, systemd</dfn></item>
      <item>Bases de donn√©es : <dfn>MongoDB, MySQL, PostGreSQL</dfn></item>
      <item>Virtualisation : <dfn>VMWare / VSphere, Virtualbox, Qemu</dfn></item>
      <item>CI / CD : <dfn>Ansible, Gitlab ci/runners, Artifactory, docker-compose</dfn></item>
      <item>Gestion de versions : je ma√Ætrise parfaitement <dfn>GIT</dfn> (int√©grateur logiciel)</item>
    </subsection>

    <subsection title="Web">
      <item>Technologies : <dfn>Javascript ES6, HTML5, CSS3, Websocket, WebRTC</dfn></item>
      <item>Frameworks : <dfn>VueJS, AngularJS, PolymerJS</dfn></item>
      <item>Packaging et tests : <dfn>Docker, npm, mocha, ava, ajv, ESLint/xo</dfn></item>
      <item>Serveurs : <dfn>Nginx, Apache, ExpressJS, Django</dfn></item>
    </subsection>

    <subsection title="R√©seau et plateformes">
      <item>R√©seau : <dfn>VLAN, Wi-Fi, Load Balancer, routage, sharding</dfn></item>
      <item>Services : <dfn>DHCP, proxy, reverse-proxy, SSH, VPN</dfn></item>
      <item>Protocoles : <dfn>HTTP, SSL/TLS, HLS, DNS, PC/SC</dfn></item>
      <item>Cloud : <dfn>GCP, OVH Cloud, Azure</dfn></item>
    </subsection>

    <subsection title="Avant-vente">
      <item>R√©ponse √† appel d'offre, soutenances, pr√©sentations et formations.</item>
      <item>R√©alisation de kits de d√©monstration, showrooms multi-produit et multi-lingue.</item>
      <item>Adaptations clientes sp√©cifiques, gestion de budget, gestion de projet.</item>
      <item><dfn>Key Account Manager</dfn> √† l'international, d√©ploiements, support N3.</item>
    </subsection>

    <subsection title="Langues" class="table">
      <item>Anglais (courant, TOEIC 905)</item>
      <item>Italien (courant, emploi en Italie)</item>
      <item>Espagnol (interm√©diaire, √©tudes en Espagne)</item>
      <item>Allemand (d√©butant, stage en Allemagne)</item>
    </subsection>
  </section>

  <section title="Loisirs">
    <item>üß≥ rencontres interculturelles (Bretagne, Bosnie-Herz√©govine, Serbie, Allemagne), voyages en inter-rail, membre actif de la communaut√© <a href="https://www.couchsurfing.com/people/clementdesiles">CouchSurfing</a>.</item>
    <item>üéµ passionn√© de concerts et de festivals de musique, je joue du piano depuis mes 6 ans, de la fl√ªte irlandaise et j‚Äôapprends le violon.</item>
    <item>üßó je pratique l‚Äôultimate frisbee, et suis amateur d‚Äôescalade et de kayak. J‚Äôadore cuisiner de (d√©licieuses) lasagnes open source.</item>
  </section>
</cv>

=== jokesterfr/cvlyzer/src/cv_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/cv2html5.xsl"?>

<cv lang="en" suffix="_clement_desiles_2020">
  <contact title="Contact">
    <name title="Name">ClÃ©ment DÃ©siles</name>
    <title>Senior Node.js developer &amp; Presales engineer</title>
    <info>31 - driving licence</info>
    <phone>+33 6 58 12 45 61</phone>
    <email>clementdesilesfr@gmail.com</email>
    <homepage>https://clementdesiles.fr</homepage>
    <photo width="128">img/photo.png</photo>
    <keywords>curriculum vitae, resume, pre-sales, lead dev, full-stack, Node.js, Linux, CI, CD, Docker, Ansible</keywords>
  </contact>

  <section title="Experience">
    <subsection title="Presales Engineer, Hoppen (ex. TÃ©lÃ©com SantÃ©), Rennes" date="since June 2016 â€“ 4 years">
      <item>Presales: design and setup of demo kits, showrooms, answer calls to tenders, witness rooms, costings.</item>
      <item>Export: technical support to international sales (Portugal, Switzerland, Quatar, Saudi Arabia...), answser to tenders, demos, deployments being Key Account Manager.</item>
      <item>Lead dev: <dfn>Docker</dfn> packaging, migration of 800 <dfn>Gitlab</dfn> projects, CI/CD setups (<dfn>Gitlab Runners</dfn>, <dfn>Ansible</dfn>, <dfn>Artifactory</dfn>). <dfn>Jira</dfn> deployment for our 300 employees.</item>
      <item>Interconnexion: medical records, medical imaging, meal ordering, invoicing, <dfn>CMMS</dfn>, <dfn>SSO</dfn>, home automation (<dfn>Siemens</dfn>, <dfn>KNX</dfn>).</item>
      <item>Security: risk assessment, hardening, technology intelligence, payment and authentication systems.</item>
      <item>Accessibility: POC of an HMI dedicated to disabled people with telethesis, eye tracking, and communication apps.</item>
    </subsection>
    <subsection title="Software architect, Revevol, Milan" date="May 2015 to May 2016 â€“ 1 year">
      <item>International intranet of 60,000 users for Lagarge-Holcim: devops of a <dfn>Google App Engine</dfn> application.</item>
      <item>Airliquide's datacenter archives migration to the cloud: design of a distributed web app (US/Europe) with <dfn>MongoDB shards</dfn>, hosted on the <dfn>GCP</dfn>.</item>
      <item>IT tool to manage Solvay's mobile devices: developement of a web app to grant accesses to Google services from a pool of 30,000 devices in the company's domain (<dfn>Apps for Work</dfn>).</item>
    </subsection>
    <subsection title="Full-stack developer, TÃ©lÃ©com SantÃ©, Rennes" date="September 2012 to April 2015 â€“ 3 years and 6 months">
      <item>Software development: lead developer of a micro-services platform for healthcare institutions. Webapps with responsive design and i18n, legacy code migration.</item>
      <item>Management: project coordination, training and skills transfer.</item>
      <item>Process and quality: analysis, specifications, system integration, tests, packaging.</item>
      <item>System: touchscreen devices support under <dfn>Linux</dfn>, <dfn>reverse engineering</dfn>, <dfn>C</dfn> bindings to <dfn>Node.js</dfn>.</item>
    </subsection>
    <subsection title="Engineer internship, TÃ©lÃ©com SantÃ©, Rennes" date="February 2012 to August 2012 â€“ 6 months">
      <item>At the very begining of a promising startup (2 founders, one senior developer and me), entire setup of a touchscreen device dedicated to patients in hospitals.</item>
      <item><dfn>Linux</dfn> support, <dfn>Vanilla JS</dfn> Web applications and <dfn>Node.js (v0.6)</dfn> backends.</item>
    </subsection>
    <subsection title="Freelance, software development" date="September 2011 to August 2012 â€“ 1 year">
      <item>Realization of an e-commerce platform for <dfn>WorldGift</dfn>.</item>
    </subsection>
    <subsection title="Internship, Telemotive headquarters, Munich" date="June 2010 to December 2010 â€“ 6 months">
      <item>At the heart of the automotive industry, development of <dfn>UPnP</dfn> services on embeded <dfn>Linux</dfn>/<dfn>PowerPC</dfn> log boards. Studies of <dfn>Ethernet</dfn> frames encapsulation within a <dfn>MOST</dfn> network (optic fiber). Performance analysis with (<dfn>Python</dfn>).</item>
    </subsection>
    <subsection title="Webmaster Assistant, PMB Services" date="June 2007 to June 2010 â€“ 3 years">
      <item>Contributions to a library management software in <dfn>PHP</dfn>/<dfn>MySQL</dfn>, design of custom interfaces for customers portals, development of the <a href="https://www.sigb.net">company's website</a> with the <dfn>SPIP</dfn> framework.</item>
    </subsection>
  </section>

  <section title="Education">
    <subsection title="Masterâ€™s Degree, Engineering Degree" date="2007â€“2012">
      <item>Top french engineers school of Brest (<a href="https://www.enib.fr">ENIB</a>), France</item>
    </subsection>
    <subsection title="Student mobility in Spain" date="2012">
      <item>University of Cadiz (<a href="http://www.uca.es/">UCA</a>), Spain</item>
    </subsection>
  </section>

  <section title="Languages and skills">
    <subsection title="Computer Sciences">
      <item>Languages: <dfn>Node.js, Python, C, C++, bash</dfn></item>
      <item>Adminsys: <dfn>Ubuntu, Archlinux, LFS, Ansible, systemd</dfn></item>
      <item>Databases: <dfn>MongoDB, MySQL, PostGreSQL</dfn></item>
      <item>Virtualization: <dfn>VMWare / VSphere, Virtualbox, Qemu</dfn></item>
      <item>Revision control: I fully master <dfn>GIT</dfn> (experience of being integrator)</item>
    </subsection>

    <subsection title="Web">
      <item>Technologies: <dfn>Javascript ES6, HTML5, CSS3, Websocket, WebRTC</dfn></item>
      <item>Frameworks: <dfn>VueJS, AngularJS, PolymerJS</dfn></item>
      <item>Packaging and testing: <dfn>Docker, npm, mocha, ava, ajv, ESLint/xo</dfn></item>
      <item>Servers: <dfn>Nginx, Apache, ExpressJS, Django</dfn></item>
    </subsection>

    <subsection title="Networking and platforms">
      <item>Networking: <dfn>VLAN, Wi-Fi, load-balancer, routing, sharding</dfn></item>
      <item>Services: <dfn>DHCP, proxy, reverse-proxy, SSH, VPN</dfn></item>
      <item>Protocols: <dfn>HTTP, SSL/TLS, HLS, DNS, PC/SC</dfn></item>
      <item>Cloud: <dfn>GCP, OVH Cloud, Azure</dfn></item>
    </subsection>

    <subsection title="Presales">
      <item>Tender answers, defense, presentation and training.</item>
      <item>Demo kits design &amp; setup, multi-product internationalized showrooms.</item>
      <item>Specific client customization, budget and project management.</item>
      <item>International <dfn>Key Account Manager</dfn>, deploys, L3 support.</item>
    </subsection>

    <subsection title="Languages" class="table">
      <item>French (native)</item>
      <item>English (fluent, TOEIC 905)</item>
      <item>Italian (fluent, work in Italy)</item>
      <item>Spanish (intermediate, studies in Spain)</item>
      <item>German (basics, internship in Germany)</item>
    </subsection>
  </section>

  <section title="Hobbies">
    <item>ðŸ§³ I've been participating to intercultural workcamps (Brittany, Bosnia-Herzegovina, Serbia, Germany), I did inter-rail travels and I'm an active member of <a href="https://www.couchsurfing.com/people/clementdesiles">CouchSurfing</a>.</item>
    <item>ðŸŽµ I've played the piano since the age of 6, the irish tin whistle, I'm now learning the violin.</item>
    <item>ðŸ§— I practice ultimate frisbee, I also do kayak and climbing. I love to cook (delicious) open-source lasagna.</item>
  </section>
</cv>

=== jokesterfr/cvlyzer/data/cv_en.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "cv.dtd">
<?xml-stylesheet type="text/xsl" href="../xsl/cv2html5.xsl"?>

<cv lang="en" suffix="_clement_desiles_2020">
  <contact title="Contact">
    <name title="Name">ClÃ©ment DÃ©siles</name>
    <title>Engineering manager</title>
    <info>31 years old</info>
    <phone>+33 6 58 12 45 61</phone>
    <email>jobs@clementdesiles.fr</email>
    <homepage>https://clementdesiles.fr</homepage>
    <photo width="128">img/photo.png</photo>
    <keywords>ClÃ©ment, DÃ©siles, curriculum vitae, resume, engineering manager, lead dev, fullstack, Node.js, Linux, CI, CD, Docker, Ansible</keywords>
  </contact>

  <section title="Experience">
    <subsection title="Presales engineer, Hoppen (ex. TÃ©lÃ©com SantÃ©), Rennes (France)" date="since June 2016 â€“ 4 years">
      <item>Presales: call for tenders (public, private), design and setup of demo kits, showrooms, witness rooms, and costings.</item>
      <item>Export: Key Account Manager of deployments and demos, engineering technical officer of international sales (Europe, UK, Middle East), co-organization and participation to top international exhibitions (ex: Arab Health).</item>
      <item>Lead dev: on a mission to increase quality and productivity, structuring tools and practices of our growing technical teams. Hoppen counts 300+ employees by 2020.</item>
      <item>Interoperability with: medical records, medical imaging, meal ordering, invoicing, <dfn>CMMS</dfn>, <dfn>SSO</dfn>, and home automation (<dfn>Siemens</dfn>, <dfn>KNX</dfn>).</item>
      <item>Security: risk assessment, hardening, audit and monitoring, experience with payment and authentication systems.</item>
      <item>Accessibility: responsible from R&amp;D budget estimation to protoype deployment of an HMI dedicated to disabled people. Telethesis, eye tracking, and communication apps.</item>
    </subsection>
    <subsection title="Software architect, Revevol, Milan (Italy)" date="May 2015 to May 2016 â€“ 1 year">
      <item>Design and devops of a <dfn>Google App Engine</dfn> application for the Lafarge-Holcim (global leader in building materials) intranet. 60,000 users.</item>
      <item>Air Liquide's datacenter archives migration to the cloud: design of a distributed web app (US/Europe) with <dfn>MongoDB shards</dfn>, hosted on the <dfn>GCP</dfn>.</item>
      <item>Maintenance of an IAM <dfn>Google Apps for Work</dfn> tool to manage Solvay's (chemicals company) 30,000 devices.</item>
    </subsection>
    <subsection title="Lead developer, TÃ©lÃ©com SantÃ©, Rennes (France)" date="September 2012 to April 2015 â€“ 3 years and 6 months">
      <item>Full stack development: micro-services platform for healthcare institutions. Webapps with responsive design and <dfn>i18n</dfn>.</item>
      <item>Management: project coordination, training and skills transfer, legacy code migration strategy.</item>
      <item>Process and quality: strong involvment in specifications, system integration, tests, and packaging.</item>
      <item>Embeded systems: experience with <dfn>Linux</dfn> drivers (ex: touchscreen), <dfn>C/C++</dfn> bindings to other languages (ex: <dfn>Node.js</dfn>).</item>
    </subsection>
    <subsection title="Engineer internship, TÃ©lÃ©com SantÃ©, Rennes (France)" date="February 2012 to August 2012 â€“ 6 months">
      <item>At the very begining of a promising startup (2 founders, one senior developer and me), design of the flagship product: a touchscreen device dedicated to patients in hospitals. Web technologies (<dfn>JavaScript</dfn>, <dfn>Node.js</dfn>), <dfn>Linux</dfn> and open source ecosystem.</item>
    </subsection>
    <subsection title="Freelance, software development" date="September 2011 to August 2012 â€“ 1 year">
      <item>Development of an e-commerce platform for a company based in the UK.</item>
    </subsection>
    <subsection title="Internship, Telemotive, Munich (Germany)" date="June 2010 to December 2010 â€“ 6 months">
      <item>At the heart of the automotive industry, development of <dfn>UPnP</dfn> services on an embeded <dfn>Linux/PowerPC</dfn> data logger solution. Research of <dfn>ethernet</dfn> frames encapsulation within a <dfn>MOST</dfn> network (optic fiber). Performance analysis with <dfn>Python</dfn>.</item>
    </subsection>
    <subsection title="Webmaster Assistant, PMB Services" date="June 2007 to June 2010 â€“ 3 years">
      <item>Contributions to an integrated library system (<dfn>ILS</dfn>) in <dfn>PHP/MySQL</dfn>, UI/UX design for customers portals, development of the company's website with the <dfn>SPIP</dfn> framework. Student job.</item>
    </subsection>
  </section>

  <section title="Skills">

    <subsection title="Presales">
      <item>Strong written and oral communications skills with the ability to present complex topics to technical and non-technical audiences.</item>
      <item>Flexible, dependable, and capable of quickly learning new products and technologies.</item>
      <item>Detailed knowledge of relevant product line specifications, performance criteria and applications.</item>
      <item>Excellent problem solving skills; ability to push creative thinking beyond the boundaries of existing industry practices and client mindsets.</item>
      <item>Ability to build strong relationships with internal and external stakeholders.</item>
      <item>Good business judgment, ability to make decisions and quotations.</item>
    </subsection>

    <subsection title="Computer science / IT">
      <item>Programming: <dfn>Node.js, Python, C, C++, bash</dfn></item>
      <item>Databases: <dfn>relational (MySQL, PostgreSQL), document stores (MongoDB, Google Cloud Datastore), columnar (BigQuery)</dfn></item>
      <item>Virtualization: <dfn>VMWare/VSphere, VitualBox, QEMU</dfn></item>
      <item>Revision control: advanced experience with <dfn>Git</dfn>, version and release management (ex: <dfn>docker, npm, artifactory, gitlab runners</dfn>)</item>
    </subsection>

    <subsection title="Web">
      <item>Core technologies: <dfn>Javascript ES6, HTML5, CSS3, WebSocket, WebRTC</dfn></item>
      <item>Frameworks: <dfn>ExpressJS, VueJS, AngularJS, PolymerJS</dfn></item>
    </subsection>

    <subsection title="Networks and services">
      <item>Networks: <dfn>VLAN, Wi-Fi, routing, DHCP, SSH, VPN, proxy, firewalls, wireshark</dfn></item>
      <item>System: administration (ex: <dfn>Ubuntu, Archlinux, LFS</dfn>), provisioning (ex: <dfn>Ansible, systemd</dfn>)</item>
      <item>Services: <dfn>DHCP, proxy, reverse-proxy, SSH, VPN</dfn></item>
      <item>Web: <dfn>HTTP, SSL/TLS, DNS, reverse-proxy, sharding, load-balancer (ex: Nginx)</dfn></item>
      <item>Cloud experience: <dfn>Google Cloud Platform</dfn> (<dfn>SFEIR</dfn> training), <dfn>OVH Cloud, Microsoft Azure</dfn></item>
    </subsection>

    <subsection title="Languages" class="table">
      <item>French: native</item>
      <item>Spanish: intermediate, student mobility in Spain</item>
      <item>English: fluent (TOEIC 905), multiple business trips abroad</item>
      <item>German: basic, internship in Germany</item>
      <item>Italian: fluent, work experience in Italy</item>
    </subsection>
  </section>

  <section title="Education">
    <subsection title="Masterâ€™s degree, engineering degree" date="2007â€“2012">
      <item>Top French engineering school of Brest (<a href="https://www.enib.fr">ENIB</a>), France</item>
    </subsection>
    <subsection title="Student mobility" date="2012">
      <item>University of Cadiz (<a href="http://www.uca.es/">UCA</a>), Spain</item>
    </subsection>
  </section>

  <section title="Hobbies">
    <item>ðŸ§³ I've participated in intercultural workcamps (Brittany, Bosnia-Herzegovina, Serbia, Germany), I did multiple inter-rail travels and I'm an active member of the CouchSurfing community.</item>
    <item>ðŸŽµ I play the piano since the age of 6, and the irish tin whistle. I'm now learning the violin.</item>
    <item>ðŸ§— I practice ultimate frisbee, I also do kayak and rock climbing. I love to cook (delicious) open-source lasagna.</item>
  </section>
</cv>
